# Generated by Django 4.0.6 on 2022-07-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='DateofJoining',
            new_name='DateOfJoining',
        ),
    ]
